POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Google",
    "author": "Alphabet",
    "url": "http://google.com",
    "likes": "1337"
}

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "devnull",
    "author": "nobody",
    "url": "http://0.0.0.0",
    "likes": "0"
}
